post_install() {

  # Set extension version validation back to default value as
  # we don't want incompatible extensions being loaded and causing breakage
  # Don't launch new dbus session
  PID="$(pgrep gnome-session)"
  export DBUS_SESSION_BUS_ADDRESS="$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/${PID}/environ)"
  gsettings set org.gnome.shell disable-extension-version-validation 'false'
}

post_upgrade() {
  post_install
}
